# Generated by Django 2.0.5 on 2018-09-13 03:08
from django.db import migrations

def seed(apps, schema_editor):
    Post = apps.get_model('scribble', 'Post')
    Comment = apps.get_model('scribble', 'Comment')

    post1 = Post(author = "J.K. Rowling", title = "Harry Potter", body = "Harry Potter is a good book, you should read it.")
    post1.save()

    comment1 = Comment(post = post1, author = "J.K. Rowling", body = "Agree, read it.")
    comment1.save()
    comment2 = Comment(post = post1, author = "J.K. Rowling", body = "kid's book.")
    comment2.save()

def fallow(apps, schema_editor):
    Post = apps.get_model('scribble', 'Post')
    Comment = apps.get_model('scribble', 'Comment')
    Post.objects.all().delete()
    Comment.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('scribble', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed, fallow)
    ]

# Harry Potter - J.K. Rowling
# The Great Gatsby - F. Scott Fitzgerald
# To Kill a Mockingbird - Harper Lee
# The Hobbit - J.R.R. Tolkien
# The Da Vinci Code - Dan Brown
# Life of Pi - Yann Martel
# Gone with the Wind - Margaret Mitchell