# Generated by Django 2.0.5 on 2018-09-13 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scribble', '0002_auto_20180913_0308'),
    ]

    operations = [
    ]
